### ISSUE TITLE
fix CORS for production

### ISSUE THREAD

**Issue by mikaeleythor** [Akongstad/DevOps-group-p#126]
see [this](https://stackoverflow.com/questions/52309527/cors-failes-when-using-docker-containers-for-frontend-and-backend)

**Comment by Akongstad** [comment]
I think the issue is that we are trying to access an http source on a https origin, which is not allowed on modern browsers
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
Just using  https://minitwit.online/api should work.
