### ISSUE TITLE
Login and Register DONT WORK HELP

### ISSUE THREAD

**Issue by mikaeleythor** [Akongstad/DevOps-group-p#131]

**Comment by mikaeleythor** [comment]
Button just redircets me to public timeline which SUCKS

**Comment by mikaeleythor** [comment]
@Blyth77

On successful register/login redirect to user timeline,hosted at:
`minitwit.online/api/msgs/<username>`

**Comment by Akongstad** [comment]
Authentication and authorization using jwt tokens in the backend implemented in  #164
