### ISSUE TITLE
Core frontend functionality

### ISSUE THREAD

**Issue by ChristianGerdes** [Akongstad/DevOps-group-p#134]
Hi,

As instructed, we've tested a few critical features and we've found a few issues:

- Do you see a public timeline? ✅
- Does the public timeline show messages that the application received from the simulator? ✅ (we think so)
- Can you create a new user? ❌ (we don't know if our user was created since we can't sign in)
- Can you login as a new user? ❌ (we don't know if login works or we just provided an invalid user)
- Can you write a message? ❌ (we can't login, so we don't know)
- After publishing a message, does it appear on you private timeline? ❌ (we can't login, so we don't know)
- Can you follow another user? ❌ (we can't login, so we don't know)

Tests performed by Christian, Lars and Tobias.

Please let us know if we're doing something wrong 😄

**Comment by mikaeleythor** [comment]
- [ ] Public timeline
- [ ] Register functionality in frontend
- [ ] Login functionality in frontend
- [ ] Private timeline when logged in
- [ ] Write message functionality in frontend
- [ ] Follow functionality in frontend
