### ISSUE TITLE
1)  Enhance your CI Pipelines with at least three static analysis tools

### ISSUE THREAD

**Issue by Stribe02** [Akongstad/DevOps-group-p#159]
- [x] add Snyk - is required by the [task](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_07/README_TASKS.md#1-enhance-your-ci-pipelines-with-at-least-three-static-analysis-tools)
- [x] add one other static tool - this can be .Net analyzers if it is. Checked if pull request is accepted
- [x] add another static tool - does codeql count?

FRIENDLY REMINDER: they need to be in the CI pipeline - aka be as github actions

- for other tools we have some options, these are for C#:
  - [Wintellect.Analyzers](https://github.com/Wintellect/Wintellect.Analyzers)
    - uses Microsoft's new Roslyn compiler
    - can used for Design analyzers, Documentation, Formatting, Performance and Usage
    - uses Apache License 2.0
    - tried this tool with default settings, it seems to be quite throughout in its scannings
      - this includes missing documentation when exceptions are explicitly thrown (counts as errors). As well as other small things it seems.
      - might want to find a way to avoid some of the warnings/ errors
  - [ArchUnitNet](https://github.com/TNG/ArchUnitNET) 
    - free, simple library for checking architecture of C# code. Can check for dependencies between classes, members, interfaces, and more. Main focus: automatically test architecture and coding rules.
    - uses Apache License 2.0
  - Testing [microsoft analysis net analyzers](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisnetanalyzers)
    - give warnings on build about stuff like missing await some places
    - gives warnings on "deference of possible null reference"

**Comment by Akongstad** [comment]
We added both codeql and deepscan
