### ISSUE TITLE
Investigate and solve follow issues

### ISSUE THREAD

**Issue by Akongstad** [Akongstad/DevOps-group-p#172]
There doesn't seem to be a problem when running the simulator he gave us. Also no problems caught by unit tests. 
But:
![image](https://user-images.githubusercontent.com/90042173/159245266-286bbe1e-48b9-4227-8afb-0f7f2304ac32.png)
The metric looking purely at return codes says alll of them return not found, while our own metrics count them at 204s. Which means at it get to the branch of the if statement in minitwitSimulator/fllws that calls follow/unfollow to minitwit, but still somehow returns 404.

This seems to also be backed up by: 
![image](https://user-images.githubusercontent.com/90042173/159245670-8350148c-9e77-459f-b8f3-be651271d4bc.png)

I guess it might be failing checks on whether the users are already following each other, but i don't know. As method should be returning 204 as long as follow is called

**Comment by mikaeleythor** [comment]
Contingent on #175

**Comment by Stribe02** [comment]
This issue got solved last week
