### ISSUE TITLE
Refactor logging services to prodserver

### ISSUE THREAD

**Issue by mikaeleythor** [Akongstad/DevOps-group-p#188]
Checkout to production branch
- [x] `filebeat.yml`
- [x] `setup_elk.sh`

Manually reconfigure on production branch
- [x] network configuration for new services
- [x] nginx proxying for new services
- [x] nginx .htpasswd volume (not sure exactly what it's for though)

Since we now have a checklist to complete before starting containers we should write a shell script for updating stuff on the server. Stuff we need to do to update our app on server

1. update .local file
2. stop containers to be updated
3. remove containers to be updated
4. pull images to be updated
5. export ELK variables/run `./setup_elk.sh`
6. build containers to be updated from new images
7. run new containers

To do this properly we need to:
- [x] Find a way to automatically update the .local file (maybe using a `git bare` repo hosted on server)
- [x] Find a way to automatically check which containers have been updated (changes to dockerfiles require image rebuild, changes to composefiles, conf-files and yml-files probably require restart)

**Comment by Akongstad** [comment]
filebeat.yml and setup_elk.sh added to app/minitwit/logging
nginx proxy setup for new services
.htpasswd generated. Found in app/minitwit
run_script.sh created. It will:
- export ELK variables/run ./setup_elk.sh
- stop containers (frontend and backend)
- remove containers (frontend and backend)
- pull images
- build and run containers
I will stop here, as i do not have time to fix stuff if deployment breaks things
TODO:
- pull production to server
- Edit deploy.yml to use run_script.sh
- I do not know what:" network configuration for new services" refers to
- Run deploy

**Comment by Akongstad** [comment]
And .htpasswd is for nginx basic_auth

**Comment by mikaeleythor** [comment]
- [ ] fix nginx volume mapping

.htpasswd could be in
`./letsencrypt/nginx/.htpasswd:/config/nginx/.htpasswd`

**or could be setup as secret in .local file**

**Comment by mikaeleythor** [comment]
```
secrets:
  htpasswd:
    file: .local/.htpasswd

services:
  letsencrypt:
    - source: htpasswd
      target: /config/nginx/.htpasswd
```

**Comment by mikaeleythor** [comment]
- [ ] Move .htpasswd to .local
- [ ] Change volume src in compose.prod.yaml to .local/.htpasswd

**Comment by mikaeleythor** [comment]
everything runs now but need to fix proxy confs

**Comment by mikaeleythor** [comment]
also need to fix deploy script such that it generates a new .htpasswd file instead of just writing saved data to it, e.g.

`htpasswd -b -c .local/.htpasswd ${{ secrets.KIBANA_USER }} ${{ secrets.KIBANA_PW }}`

**Comment by mikaeleythor** [comment]
We probably need to change **allowed hosts** on kibana or something similar to what we did with grafana.

**Comment by Akongstad** [comment]
I have create the github secrets: KIBANA_USER and KIBANA_PW
