### ISSUE TITLE
Create a cluster

### ISSUE THREAD

**Issue by mikaeleythor** [Akongstad/DevOps-group-p#274]
On DigitalOcean because of the flexibility of floating IPs.

- [x] Decide if this should be done via script or GUI
- [x] Follow through on that decision but document arguments

**Comment by Akongstad** [comment]
- [x] Create new compose-file to run database and Nginx on current droplet
- [x] Create new Nginx conf file
- [x] Create new connectionString.txt for db

**Comment by mikaeleythor** [comment]
Issue is continued in [itu-minitwit-ops](https://github.com/mikaeleythor/itu-minitwit-ops/issues/5)
