### ISSUE TITLE
Droplet out of memory

### ISSUE THREAD

**Issue by Akongstad** [Akongstad/DevOps-group-p#302]
**Describe the bug**
Droplet out of memory

**To Reproduce**
1. Use all available disk space

**Screenshots**
<img width="445" alt="image" src="https://user-images.githubusercontent.com/90042173/163942625-83859ae7-71bf-4dbe-a503-fcf8f0a2993b.png">

**Comment by mikaeleythor** [comment]
Partly solved by deleting ELK volume (which was about 5GB)

Steps to implement a temporary solution:

- [ ] Delete ELK volume
- [ ] Accept pull req #305
- [ ] Deactivate ELK stack in compose.prod
- [ ] Run ./run_script.sh
